#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
python3 - <<'PY'
import json
from pathlib import Path
paths = [
    Path('spec/FORMAL_CORE_R0.json'), Path('spec/OBSERVATION_CONTRACT_R0.json'), Path('spec/PERCEPTUAL_CHANNELS_R0.json'),
    Path('spec/VIRTUAL_MEMORY_R0.json'), Path('spec/VISUAL_MEMORY_PROFILE_R0.json'), Path('spec/VIRTUAL_MEMORY_NAV_EVAL_R0.json'),
    Path('spec/MEMORY_SCALE_LAB_R0.json'), Path('spec/FIXED_CARRIER_R2.json'), Path('spec/EVIDENCE_REDUCTION_R0.json'),
    Path('spec/SEMANTIC_SPINE_R1.json'), Path('spec/PERCEPTION_PROMOTION_R1.json'), Path('spec/CANONICAL_VISUAL_GRAMMAR_R0.json'),
    Path('spec/WRITER_R0.json'), Path('spec/HYBRID_RECEIVER_R0.json'), Path('spec/DEVELOPMENT_TOOL_BOUNDARY_R0.json'),
    Path('spec/NATIVE_SEMANTIC_NAV_R0.json'), Path('spec/ORIGAMI_PROTOCOL_R0.json'), Path('spec/CODEC_REGISTRY_R0.json'),
    Path('spec/CAPABILITY_NEGOTIATION_R0.json'), Path('spec/FIXED_CARRIER_PROFILE_3_R0.json'),
    Path('experiments/native-semantic-nav-r0/FAILED_TRIAL_001.json'), Path('experiments/memory-scale-r0/config.json'),
    Path('experiments/EXP-001-relational-state/experiment.json'), Path('changes/CHG-ORIGAMI-0009.json')
]
data={str(p):json.loads(p.read_text()) for p in paths}
formal=data['spec/FORMAL_CORE_R0.json']; obs=data['spec/OBSERVATION_CONTRACT_R0.json']; percept=data['spec/PERCEPTUAL_CHANNELS_R0.json']; vmem=data['spec/VIRTUAL_MEMORY_R0.json']; visual=data['spec/VISUAL_MEMORY_PROFILE_R0.json']; nav=data['spec/VIRTUAL_MEMORY_NAV_EVAL_R0.json']; scale=data['spec/MEMORY_SCALE_LAB_R0.json']; fixed=data['spec/FIXED_CARRIER_R2.json']; evidence=data['spec/EVIDENCE_REDUCTION_R0.json']; spine=data['spec/SEMANTIC_SPINE_R1.json']; promotion=data['spec/PERCEPTION_PROMOTION_R1.json']; grammar=data['spec/CANONICAL_VISUAL_GRAMMAR_R0.json']; writer=data['spec/WRITER_R0.json']; receiver=data['spec/HYBRID_RECEIVER_R0.json']; dev=data['spec/DEVELOPMENT_TOOL_BOUNDARY_R0.json']; native=data['spec/NATIVE_SEMANTIC_NAV_R0.json']; protocol=data['spec/ORIGAMI_PROTOCOL_R0.json']; codecs=data['spec/CODEC_REGISTRY_R0.json']; caps=data['spec/CAPABILITY_NEGOTIATION_R0.json']; profile3=data['spec/FIXED_CARRIER_PROFILE_3_R0.json']; failed=data['experiments/native-semantic-nav-r0/FAILED_TRIAL_001.json']; scale_cfg=data['experiments/memory-scale-r0/config.json']; exp=data['experiments/EXP-001-relational-state/experiment.json']; change=data['changes/CHG-ORIGAMI-0009.json']
assert formal['contract_id']=='origami.formal-core.r0'; assert obs['contract_id']=='origami.observation-contract.r0'; assert percept['observation_contract']==obs['contract_id']; assert 'LATENT_IS_FALSIFIABLE' in percept['invariants']; assert 'BUDGET_MUST_BE_FINITE' in obs['invariants']
assert vmem['contract_id']=='origami.virtual-memory.r0'; assert vmem['context_budget']['default_token_equivalent']==4000; assert 'NO_IMPLICIT_GLOBAL_EXACT_SCAN' in vmem['invariants']; assert visual['contract_id']=='origami.visual-memory-profile.r0'; assert len(visual['family_roles'])==42; assert nav['active_context_token_eq']==4000; assert nav['promotion']['false_exact_required']==0
assert scale['contract_id']=='origami.memory-scale-lab.r0'; assert scale_cfg['budget_tokens']-scale_cfg['reserve_tokens']==4000; assert scale_cfg['carrier_counts']==[1,10,100,1000]
assert fixed['contract_id']=='origami.fixed-carrier.r2'; assert fixed['physical_profile']['profile_id']=='origami.fixed-carrier.r2.profile-2'; assert fixed['physical_profile']['legacy_profile_readable']=='origami.fixed-carrier.r2.profile-1'; assert fixed['physical_profile']['frozen_png_bytes']==8192; assert fixed['physical_profile']['width_px']==640; assert fixed['physical_profile']['height_px']==640; assert fixed['semantic_plane']['index_query_requires_binary_decode'] is False; assert fixed['exact_plane']['native_semantic_dependency'] is False; assert 'T2_CONTAINS_ACTUAL_SEMANTIC_ENTRIES' in fixed['hard_invariants']; assert 'SEMANTIC_NAVIGATION_NE_MECHANICAL_DECODE' in fixed['hard_invariants']
assert evidence['contract_id']=='origami.evidence-reduction.r0'; assert evidence['boundary']['swarm_generation']=='EXTERNAL_DEVELOPMENT_OR_MODEL_SYSTEM'; assert evidence['default_policy']['min_verified_evidence']==1; assert 'ORIGAMI_REDUCTION_IS_ORDER_DETERMINISTIC' in evidence['hard_invariants']
assert spine['contract_id']=='origami.semantic-spine.r1'; assert spine['status']=='EXPERIMENTAL_REFERENCE_IMPLEMENTED'; assert spine['canonical_flow'][0]=='EXACT_SOURCE_PLANE'; assert spine['swarm_boundary']['orchestration']=='EXTERNAL_DEVELOPMENT_OR_MODEL_SYSTEM'; assert spine['swarm_boundary']['confidence_authority'] is False
assert promotion['contract_id']=='origami.perception-promotion.r1'; assert promotion['evidence_kinds']['MOCK'].startswith('May validate harness'); assert 'MOCK_NE_EMPIRICAL_PROMOTION' in promotion['hard_invariants']; assert 'PRIVATE_GROUND_TRUTH_NE_MODEL_INPUT' in promotion['hard_invariants']
assert protocol['contract_id']=='origami.protocol.r0'; assert protocol['required_properties']['read_write_bidirectional'] is True; assert protocol['required_properties']['carrier_independent_semantics'] is True; assert protocol['roundtrip']['equation']=='DECODE(ENCODE(S)) ~= S'; assert 'PROTOCOL_NE_CARRIER' in protocol['hard_invariants']
assert codecs['contract_id']=='origami.codec-registry.r0'; assert codecs['roundtrip']['first_required_pair']=='S2_E2'; assert codecs['selection']['semantic_before_exact'] is True; assert codecs['semantic_decoders'][2]['id']=='S2'; assert codecs['semantic_encoders'][2]['id']=='E2'; assert 'S_CODEC_DOES_NOT_HIDE_X_DEPENDENCY' in codecs['hard_invariants']
assert caps['contract_id']=='origami.capability-negotiation.r0'; assert caps['core_profile']['exact_plane_required'] is False; assert 'S2' in caps['core_profile']['required']; assert 'E2' in caps['core_profile']['required']; assert caps['failure_behavior']['EXACT_READ']=='NOT_VERIFIED'; assert 'UNSUPPORTED_CAPABILITY_NE_INVENTION' in caps['hard_invariants']
assert profile3['profile_id']=='origami.fixed-carrier.r2.profile-3'; assert profile3['status']=='EXPERIMENTAL_RENDERER_IMPLEMENTED_EVIDENCE_PENDING'; assert profile3['geometry']=={'width':640,'height':640}; assert profile3['transport']['target_png_bytes']==8192; assert profile3['renderer']['implementation']=='internal/fixedcarrier.RenderProfile3'; assert profile3['renderer']['default_renderer'] is False; assert profile3['backward_compatibility']['profile_3_default_renderer'] is False; assert profile3['roundtrip_gate']=='S2(E2(INDEX)) ~= INDEX'; assert profile3['evidence_state']['deterministic_renderer_roundtrip']=='PASS_CI'; assert profile3['evidence_state']['frozen_8192_byte_envelope']=='PASS_CI'; assert profile3['evidence_state']['held_out_native_s2']=='PENDING_EXTERNAL_MODEL_TRIALS'; assert profile3['evidence_state']['promotion'] is False
assert grammar['contract_id']=='origami.canonical-visual-grammar.r0'; assert grammar['aesthetic']['carrier_specific_aesthetics'] is False; assert grammar['rosetta']['required'] is True; assert grammar['rosetta']['must_declare_decoder_registry'] is True; assert grammar['rosetta']['must_declare_encoder_registry'] is True; assert grammar['evolution']['profile_promotion_owner']=='ORIGAMI'; assert 'ROSETTA_DECLARES_DECODING_SEMANTICS' in grammar['hard_invariants']; assert 'ROSETTA_DECLARES_ENCODING_SEMANTICS' in grammar['hard_invariants']
assert writer['contract_id']=='origami.writer.r0'; assert writer['source_policy']['pdf_to_png_screenshot_forbidden'] is True; assert writer['roundtrip_gate']['required'] is True; assert writer['roundtrip_gate']['equation']=='DECODE(ENCODE(SEMANTIC_IR)) ~= SEMANTIC_IR'; assert writer['model_behavior']['may_directly_paint_arbitrary_png'] is False; assert writer['encoder_registry']['first_mandatory_write_gate']=='E2_ENCODE_SUPERINDEX'; assert writer['native_semantic_write_rule']['index_encoder']=='E2'
assert receiver['external_receiver_contract']['carrier_specific_aesthetic'] is False; assert 'ONE_CANONICAL_AESTHETIC_PER_PROFILE_VERSION' in receiver['semantic_invariants']
assert dev['contract_id']=='origami.development-tool-boundary.r0'; assert dev['portable_baseline']['artifact']=='MASTER_PROMPT_PLUS_EXPLICIT_USER_INPUT'; assert 'TLALOC' in dev['portable_baseline']['does_not_require']; assert 'SANDBOX' in dev['portable_baseline']['does_not_require']; assert 'ORIGAMI_OWNS_ORIGAMI_RELEASES' in dev['hard_invariants']
assert native['contract_id']=='origami.native-semantic-navigation.r0'; assert native['query_routes']['INDEX']==['T0','T1','S2','T2']; assert native['decoder_selection']['semantic_before_exact'] is True; assert native['decoder_selection']['undeclared_external_decoder_forbidden'] is True; assert native['t2']['must_render_actual_semantic_entries'] is True; assert native['t2']['decoder']=='S2'; assert native['t2']['encoder_pair']=='E2'; assert native['exact_plane']['required_for_semantic_index'] is False; assert native['benchmark_questions'][1]['id']=='NSN-Q2'; assert native['benchmark_questions'][1]['exact_codec_allowed'] is False; assert 'NO_UNVERIFIED_BYTE_HASH_COMPRESSION_CLAIMS' in native['hard_invariants']; assert 'FAILED_NATIVE_TRIAL_BECOMES_REGRESSION' in native['hard_invariants']; assert 'NO_UNDECLARED_EXTERNAL_DECODER_DEPENDENCY' in native['hard_invariants']
assert failed['trial_id']=='FAILED_TRIAL_001'; assert failed['observed_behavior']['boot_text_perceived'] is True; assert failed['observed_behavior']['semantic_t2_index_recovered'] is False; assert failed['observed_behavior']['invented_or_corrupted_exact_fields'] is True; assert failed['repository_reference']['hash_match'] is False
assert change['after']['version']=='6.0.0-alpha.7'; assert exp['status']=='SPECIFIED_NOT_YET_EXECUTED'
print('formal-contracts: PASS')
PY
