package microisa

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/LuigiD5555/origami/internal/lab/glyphcalc"
)

const (
	OpObserve4 = "OBSERVE4"
	OpTuple4   = "TUPLE4"
	OpDecode8  = "DECODE8"
)

type LaneTruth struct { Index int `json:"i"`; ByteHex string `json:"byte_hex"`; Shape uint8 `json:"shape"`; Holes uint8 `json:"holes"`; Direction uint8 `json:"direction"`; Frames uint8 `json:"frames"` }
type ProbeSpec struct { Schema string `json:"schema"`; ProbeID string `json:"probe_id"`; Op string `json:"op"`; LaneWidth int `json:"lane_width"`; CaseIndex int `json:"case_index"`; Seed uint64 `json:"seed"`; SemanticMeaning string `json:"semantic_meaning"`; Truth []LaneTruth `json:"truth"`; PromptSHA256 string `json:"prompt_sha256"`; CarrierSHA256 string `json:"carrier_sha256"` }
type LaneResponse struct { Index int `json:"i"`; Status string `json:"status"`; Shape *uint8 `json:"shape,omitempty"`; Holes *uint8 `json:"holes,omitempty"`; Direction *uint8 `json:"direction,omitempty"`; Frames *uint8 `json:"frames,omitempty"`; ByteHex string `json:"byte_hex,omitempty"`; Tuple4 string `json:"tuple4,omitempty"` }
type UsageMetrics struct { LatencyMS float64 `json:"latency_ms,omitempty"`; InputTokens int `json:"input_tokens,omitempty"`; OutputTokens int `json:"output_tokens,omitempty"`; Retries int `json:"retries,omitempty"`; Cost float64 `json:"cost,omitempty"` }
type Response struct { Schema string `json:"schema"`; Model string `json:"model"`; Status string `json:"status"`; Lanes []LaneResponse `json:"lanes"`; Metrics UsageMetrics `json:"metrics,omitempty"` }
type Score struct { Schema string `json:"schema"`; ProbeID string `json:"probe_id"`; Model string `json:"model"`; Op string `json:"op"`; LaneWidth int `json:"lane_width"`; TotalLanes int `json:"total_lanes"`; ExactKnown int `json:"exact_known"`; FalseKnown int `json:"false_known"`; Unknown int `json:"unknown"`; InvalidOrMissing int `json:"invalid_or_missing"`; ExactKnownRate float64 `json:"exact_known_rate"`; FalseKnownRate float64 `json:"false_known_rate"`; SafeFalseExact bool `json:"safe_false_exact"`; Metrics UsageMetrics `json:"metrics,omitempty"` }
type ProfileRow struct { Model string `json:"model"`; Op string `json:"op"`; LaneWidth int `json:"lane_width"`; Cases int `json:"cases"`; TotalLanes int `json:"total_lanes"`; ExactKnown int `json:"exact_known"`; FalseKnown int `json:"false_known"`; Unknown int `json:"unknown"`; InvalidOrMissing int `json:"invalid_or_missing"`; ExactKnownRate float64 `json:"exact_known_rate"`; FalseKnownRate float64 `json:"false_known_rate"`; MeanLatencyMS float64 `json:"mean_latency_ms,omitempty"`; OutputTokensPerLane float64 `json:"output_tokens_per_lane,omitempty"`; CostPerLane float64 `json:"cost_per_lane,omitempty"`; Safe bool `json:"safe"` }
type Profile struct { Schema string `json:"schema"`; Policy string `json:"policy"`; MinimumExactKnownRate float64 `json:"minimum_exact_known_rate"`; Rows []ProfileRow `json:"rows"`; RecommendedObserveWidth int `json:"recommended_observe4_width"`; RecommendedTupleWidth int `json:"recommended_tuple4_width"`; RecommendedDecodeWidth int `json:"recommended_decode8_width"`; Interpretation string `json:"interpretation"` }

func PrepareCampaign(root string, widths []int, cases int, seed uint64) error {
	if cases <= 0 { return fmt.Errorf("cases must be >0") }
	for _, w := range widths { if w <= 0 || w > 64 { return fmt.Errorf("invalid lane width %d", w) } }
	if err := os.MkdirAll(root, 0o755); err != nil { return err }
	var queue []string
	for _, op := range []string{OpObserve4, OpTuple4, OpDecode8} { for _, w := range widths { for c := 0; c < cases; c++ { dir := filepath.Join(root, strings.ToLower(op), fmt.Sprintf("w%02d", w), fmt.Sprintf("c%02d", c)); if err := PrepareProbe(dir, op, w, c, seed); err != nil { return err }; queue = append(queue, fmt.Sprintf("%s\tw=%d\tcase=%d\t%s", op, w, c, filepath.ToSlash(dir))) } } }
	return os.WriteFile(filepath.Join(root, "QUEUE.tsv"), []byte("# Execute in this order. Stop widening after the first FALSE_KNOWN.\n"+strings.Join(queue,"\n")+"\n"), 0o644)
}

func PrepareProbe(dir, op string, width, caseIndex int, masterSeed uint64) error {
	if op != OpObserve4 && op != OpTuple4 && op != OpDecode8 { return fmt.Errorf("unsupported op %s", op) }
	if err := os.MkdirAll(filepath.Join(dir, "blind"), 0o755); err != nil { return err }
	seed := derive(masterSeed, op, width, caseIndex); bytesIn := make([]byte,width); x:=seed
	for i:=range bytesIn { x+=0x9e3779b97f4a7c15; z:=x; z=(z^(z>>30))*0xbf58476d1ce4e5b9; z=(z^(z>>27))*0x94d049bb133111eb; z^=z>>31; bytesIn[i]=byte(z^uint64(i*73+caseIndex*29)) }
	glyphs:=glyphcalc.GlyphsFromBytes(bytesIn); cols:=width; if cols>8{cols=8}; pngb,_,err:=glyphcalc.RenderGlyphGrid(glyphs,cols,68,20); if err!=nil{return err}
	prompt:=promptFor(op,width); query:=queryFor(op,width); truth:=make([]LaneTruth,len(glyphs)); for i,g:=range glyphs{truth[i]=LaneTruth{Index:i,ByteHex:fmt.Sprintf("%02x",g.Byte),Shape:g.Shape,Holes:g.Holes,Direction:g.Direction,Frames:g.Frames}}
	ps:=ProbeSpec{Schema:"ohf.microisa.probe.v1",Op:op,LaneWidth:width,CaseIndex:caseIndex,Seed:seed,SemanticMeaning:"NONE",Truth:truth,PromptSHA256:hash([]byte(prompt)),CarrierSHA256:hash(pngb)}; ps.ProbeID=hash([]byte(fmt.Sprintf("%s|%s|%d|%d|%d|%s|%s",ps.Schema,op,width,caseIndex,seed,ps.PromptSHA256,ps.CarrierSHA256)))[:16]
	b,_:=json.MarshalIndent(ps,"","  "); b=append(b,'\n'); if err:=os.WriteFile(filepath.Join(dir,"probe.json"),b,0o644);err!=nil{return err}; if err:=os.WriteFile(filepath.Join(dir,"blind","carrier.png"),pngb,0o644);err!=nil{return err}; if err:=os.WriteFile(filepath.Join(dir,"blind","MASTER_PROMPT.md"),[]byte(prompt),0o644);err!=nil{return err}; if err:=os.WriteFile(filepath.Join(dir,"blind","query.txt"),[]byte(query),0o644);err!=nil{return err}; return os.WriteFile(filepath.Join(dir,"response.template.json"),[]byte(responseTemplate(op,width)),0o644)
}

func ScoreResponse(caseDir,responsePath string)(Score,error){pb,err:=os.ReadFile(filepath.Join(caseDir,"probe.json"));if err!=nil{return Score{},err};var p ProbeSpec;if err:=json.Unmarshal(pb,&p);err!=nil{return Score{},err};rb,err:=os.ReadFile(responsePath);if err!=nil{return Score{},err};var r Response;if err:=json.Unmarshal(rb,&r);err!=nil{return Score{},err};byIndex:=map[int]LaneResponse{};for _,lane:=range r.Lanes{byIndex[lane.Index]=lane};s:=Score{Schema:"ohf.microisa.score.v1",ProbeID:p.ProbeID,Model:r.Model,Op:p.Op,LaneWidth:p.LaneWidth,TotalLanes:len(p.Truth),Metrics:r.Metrics};for _,t:=range p.Truth{rr,ok:=byIndex[t.Index];if !ok{s.InvalidOrMissing++;continue};st:=strings.ToUpper(rr.Status);if st=="UNKNOWN"||st=="AMBIGUOUS"{s.Unknown++;continue};if st!="KNOWN"{s.InvalidOrMissing++;continue};correct:=false;switch p.Op{case OpObserve4:correct=rr.Shape!=nil&&rr.Holes!=nil&&rr.Direction!=nil&&rr.Frames!=nil&&*rr.Shape==t.Shape&&*rr.Holes==t.Holes&&*rr.Direction==t.Direction&&*rr.Frames==t.Frames;case OpTuple4:correct=rr.Tuple4==fmt.Sprintf("%d%d%d%d",t.Shape,t.Holes,t.Direction,t.Frames);case OpDecode8:correct=strings.ToLower(strings.TrimPrefix(rr.ByteHex,"0x"))==t.ByteHex};if correct{s.ExactKnown++}else{s.FalseKnown++}};if s.TotalLanes>0{s.ExactKnownRate=float64(s.ExactKnown)/float64(s.TotalLanes);s.FalseKnownRate=float64(s.FalseKnown)/float64(s.TotalLanes)};s.SafeFalseExact=s.FalseKnown==0;out,_:=json.MarshalIndent(s,"","  ");out=append(out,'\n');if err:=os.WriteFile(filepath.Join(caseDir,"score.json"),out,0o644);err!=nil{return Score{},err};return s,nil}

func BuildProfile(root string, minimumExactKnownRate float64)(Profile,error){type key struct{model,op string;width int};rows:=map[key][]Score{};err:=filepath.Walk(root,func(path string,info os.FileInfo,err error)error{if err!=nil{return err};if info==nil||info.IsDir()||info.Name()!="score.json"{return nil};b,e:=os.ReadFile(path);if e!=nil{return e};var s Score;if e=json.Unmarshal(b,&s);e!=nil{return e};rows[key{s.Model,s.Op,s.LaneWidth}]=append(rows[key{s.Model,s.Op,s.LaneWidth}],s);return nil});if err!=nil{return Profile{},err};prof:=Profile{Schema:"ohf.microisa.profile.v1",Policy:"FALSE_EXACT=0; choose widest lane width meeting minimum exact-known rate",MinimumExactKnownRate:minimumExactKnownRate,Interpretation:"Logical lane batching reduces serial dependency; it does not claim controllable hardware-level parallelism inside the model."};keys:=make([]key,0,len(rows));for k:=range rows{keys=append(keys,k)};sort.Slice(keys,func(i,j int)bool{if keys[i].model!=keys[j].model{return keys[i].model<keys[j].model};if keys[i].op!=keys[j].op{return keys[i].op<keys[j].op};return keys[i].width<keys[j].width});for _,k:=range keys{ss:=rows[k];r:=ProfileRow{Model:k.model,Op:k.op,LaneWidth:k.width,Cases:len(ss)};var lat float64;var latN,outTok int;var cost float64;for _,s:=range ss{r.TotalLanes+=s.TotalLanes;r.ExactKnown+=s.ExactKnown;r.FalseKnown+=s.FalseKnown;r.Unknown+=s.Unknown;r.InvalidOrMissing+=s.InvalidOrMissing;if s.Metrics.LatencyMS>0{lat+=s.Metrics.LatencyMS;latN++};outTok+=s.Metrics.OutputTokens;cost+=s.Metrics.Cost};if r.TotalLanes>0{r.ExactKnownRate=float64(r.ExactKnown)/float64(r.TotalLanes);r.FalseKnownRate=float64(r.FalseKnown)/float64(r.TotalLanes);r.OutputTokensPerLane=float64(outTok)/float64(r.TotalLanes);r.CostPerLane=cost/float64(r.TotalLanes)};if latN>0{r.MeanLatencyMS=lat/float64(latN)};r.Safe=r.FalseKnown==0&&r.ExactKnownRate>=minimumExactKnownRate;prof.Rows=append(prof.Rows,r);if r.Safe&&r.Op==OpObserve4&&r.LaneWidth>prof.RecommendedObserveWidth{prof.RecommendedObserveWidth=r.LaneWidth};if r.Safe&&r.Op==OpTuple4&&r.LaneWidth>prof.RecommendedTupleWidth{prof.RecommendedTupleWidth=r.LaneWidth};if r.Safe&&r.Op==OpDecode8&&r.LaneWidth>prof.RecommendedDecodeWidth{prof.RecommendedDecodeWidth=r.LaneWidth}};b,_:=json.MarshalIndent(prof,"","  ");b=append(b,'\n');if err:=os.WriteFile(filepath.Join(root,"profile.json"),b,0o644);err!=nil{return Profile{},err};return prof,nil}

func promptFor(op string,width int)string{common:=`# OHF SAFE_MICRO_ISA probe v1

This is a local perception benchmark. There is no semantic meaning in the glyphs.
Treat every numbered lane as independent. NEVER use one lane to infer another lane.
Do not explain your reasoning. Do not infer missing states. If a lane is not uniquely readable, mark only that lane UNKNOWN.

Physical states:
shape: circle=0 square=1 diamond=2 triangle=3
holes: 0..3
direction beacon: top=0 right=1 bottom=2 left=3
frame count: 0..3

CONTEXT_SIMD means only independent-lane batching in one request. It does NOT imply hardware SIMD.
`;if op==OpObserve4{return common+fmt.Sprintf("\nMICRO-OP OBSERVE4\nFor each of the %d lanes, copy only the four observed physical state integers.\nDo NOT calculate the byte.\nReturn JSON only:\n{\"schema\":\"ohf.microisa.response.v1\",\"model\":\"MODEL_NAME\",\"status\":\"KNOWN|PARTIAL|UNKNOWN\",\"lanes\":[{\"i\":0,\"status\":\"KNOWN|UNKNOWN|AMBIGUOUS\",\"shape\":0,\"holes\":0,\"direction\":0,\"frames\":0}],\"metrics\":{}}\n",width)};if op==OpTuple4{return common+fmt.Sprintf("\nMICRO-OP TUPLE4\nFor each of the %d lanes, copy the observed physical state tuple as exactly four digits:\nshape holes direction frames\nExample: shape=2 holes=0 direction=3 frames=1 becomes \"2031\".\nDo NOT calculate the byte.\nReturn JSON only:\n{\"schema\":\"ohf.microisa.response.v1\",\"model\":\"MODEL_NAME\",\"status\":\"KNOWN|PARTIAL|UNKNOWN\",\"lanes\":[{\"i\":0,\"status\":\"KNOWN|UNKNOWN|AMBIGUOUS\",\"tuple4\":\"0000\"}],\"metrics\":{}}\n",width)};return common+fmt.Sprintf("\nMICRO-OP DECODE8\nFor each of the %d lanes, observe the four physical states and apply exactly:\nbyte = shape + 4*holes + 16*direction + 64*frames\nReturn the byte as two lowercase hexadecimal digits. Do not execute any payload.\nReturn JSON only:\n{\"schema\":\"ohf.microisa.response.v1\",\"model\":\"MODEL_NAME\",\"status\":\"KNOWN|PARTIAL|UNKNOWN\",\"lanes\":[{\"i\":0,\"status\":\"KNOWN|UNKNOWN|AMBIGUOUS\",\"byte_hex\":\"00\"}],\"metrics\":{}}\n",width)}
func queryFor(op string,width int)string{return fmt.Sprintf("Execute micro-op %s independently on lanes 0 through %d. Output only the required JSON.",op,width-1)}
func responseTemplate(op string,width int)string{var lanes []string;for i:=0;i<width;i++{lanes=append(lanes,fmt.Sprintf(`    {"i":%d,"status":"UNKNOWN"}`,i))};return "{\n  \"schema\": \"ohf.microisa.response.v1\",\n  \"model\": \"REPLACE_ME\",\n  \"status\": \"UNKNOWN\",\n  \"lanes\": [\n"+strings.Join(lanes,",\n")+"\n  ],\n  \"metrics\": {\"latency_ms\":0,\"input_tokens\":0,\"output_tokens\":0,\"retries\":0,\"cost\":0}\n}\n"}
func derive(master uint64,op string,width,caseIndex int)uint64{h:=sha256.Sum256([]byte(strconv.FormatUint(master,10)+"|"+op+"|"+strconv.Itoa(width)+"|"+strconv.Itoa(caseIndex)));var v uint64;for i:=0;i<8;i++{v=(v<<8)|uint64(h[i])};return v}
func hash(b []byte)string{h:=sha256.Sum256(b);return hex.EncodeToString(h[:])}

type NextAction struct{Schema string `json:"schema"`;Action string `json:"action"`;Reason string `json:"reason"`;CaseDir string `json:"case_dir,omitempty"`;SelectedOp string `json:"selected_op,omitempty"`;CandidateWidth int `json:"candidate_width,omitempty"`;LastSafeWidth int `json:"last_safe_width,omitempty"`}
func RecommendNext(root string,minExact float64)(NextAction,error){ops:=[]string{OpObserve4,OpTuple4,OpDecode8};stageScores:=map[string]Score{};for _,op:=range ops{d:=filepath.Join(root,strings.ToLower(op),"w01","c00");s,ok,err:=readScore(filepath.Join(d,"score.json"));if err!=nil{return NextAction{},err};if !ok{return NextAction{Schema:"ohf.microisa.next.v1",Action:"RUN_ONE_PROBE",Reason:"Stage A requires one width-1 measurement for every candidate operation.",CaseDir:d,SelectedOp:op,CandidateWidth:1},nil};stageScores[op]=s};safe:=[]Score{};for _,op:=range ops{s:=stageScores[op];if s.FalseKnown==0&&s.ExactKnownRate>=minExact{safe=append(safe,s)}};if len(safe)==0{return NextAction{Schema:"ohf.microisa.next.v1",Action:"STOP",Reason:"No width-1 operation satisfies FALSE_KNOWN=0 and the minimum exact-known threshold."},nil};sort.SliceStable(safe,func(i,j int)bool{a,b:=safe[i],safe[j];if a.ExactKnownRate!=b.ExactKnownRate{return a.ExactKnownRate>b.ExactKnownRate};if a.Metrics.OutputTokens>0&&b.Metrics.OutputTokens>0&&a.Metrics.OutputTokens!=b.Metrics.OutputTokens{return a.Metrics.OutputTokens<b.Metrics.OutputTokens};if a.Metrics.LatencyMS>0&&b.Metrics.LatencyMS>0&&a.Metrics.LatencyMS!=b.Metrics.LatencyMS{return a.Metrics.LatencyMS<b.Metrics.LatencyMS};pref:=map[string]int{OpTuple4:0,OpObserve4:1,OpDecode8:2};return pref[a.Op]<pref[b.Op]});chosen:=safe[0].Op;widths:=[]int{4,8,16};lastSafe:=1;firstFail:=0;for _,w:=range widths{d:=filepath.Join(root,strings.ToLower(chosen),fmt.Sprintf("w%02d",w),"c00");s,ok,err:=readScore(filepath.Join(d,"score.json"));if err!=nil{return NextAction{},err};if !ok{return NextAction{Schema:"ohf.microisa.next.v1",Action:"RUN_ONE_PROBE",Reason:"Widen only the selected operation one step at a time.",CaseDir:d,SelectedOp:chosen,CandidateWidth:w,LastSafeWidth:lastSafe},nil};if s.FalseKnown>0||s.ExactKnownRate<minExact{firstFail=w;break};lastSafe=w};safeDir:=filepath.Join(root,strings.ToLower(chosen),fmt.Sprintf("w%02d",lastSafe),"c01");if _,ok,err:=readScore(filepath.Join(safeDir,"score.json"));err!=nil{return NextAction{},err}else if !ok{return NextAction{Schema:"ohf.microisa.next.v1",Action:"RUN_BOUNDARY_CONFIRMATION",Reason:"Confirm the largest passing width with one independent case.",CaseDir:safeDir,SelectedOp:chosen,CandidateWidth:lastSafe,LastSafeWidth:lastSafe},nil};if firstFail>0{failDir:=filepath.Join(root,strings.ToLower(chosen),fmt.Sprintf("w%02d",firstFail),"c01");if _,ok,err:=readScore(filepath.Join(failDir,"score.json"));err!=nil{return NextAction{},err}else if !ok{return NextAction{Schema:"ohf.microisa.next.v1",Action:"RUN_BOUNDARY_CONFIRMATION",Reason:"Confirm the first failing width once; do not widen further.",CaseDir:failDir,SelectedOp:chosen,CandidateWidth:firstFail,LastSafeWidth:lastSafe},nil}};return NextAction{Schema:"ohf.microisa.next.v1",Action:"STOP_AND_BUILD_PROFILE",Reason:"Adaptive micro-op/lane search is complete for the supplied cases.",SelectedOp:chosen,LastSafeWidth:lastSafe},nil}
func readScore(path string)(Score,bool,error){b,err:=os.ReadFile(path);if os.IsNotExist(err){return Score{},false,nil};if err!=nil{return Score{},false,err};var s Score;if err=json.Unmarshal(b,&s);err!=nil{return Score{},false,err};return s,true,nil}
