package core

import("fmt";"sort";"strings")
type appliedEffect struct{RuleID string;Effect Effect}

func Step(state State,context Context,machine Machine,stepIndex int)(State,TransitionEvidence,error){
	if err:=ValidateState(state);err!=nil{return State{},TransitionEvidence{},err};if err:=validateContext(context);err!=nil{return State{},TransitionEvidence{},err};if err:=ValidateMachine(machine);err!=nil{return State{},TransitionEvidence{},err}
	rules:=append([]Rule(nil),machine.Rules...);sort.Slice(rules,func(i,j int)bool{return rules[i].ID<rules[j].ID});fires:=[]RuleFire{};hits:=[]ContradictionHit{};byKey:=map[string][]appliedEffect{}
	for _,rule:=range rules{if !matches(rule.When,state,context){continue};participants:=predicateParticipants(rule.When);if rule.Contradiction!=nil{hits=append(hits,ContradictionHit{RuleID:rule.ID,Reason:rule.Contradiction.Reason,Participants:participants});continue};effects:=append([]Effect(nil),rule.Then...);sort.Slice(effects,func(i,j int)bool{return effectKey(effects[i])<effectKey(effects[j])});fires=append(fires,RuleFire{RuleID:rule.ID,Participants:participants,Effects:effects});for _,effect:=range effects{byKey[effect.Key]=append(byKey[effect.Key],appliedEffect{RuleID:rule.ID,Effect:effect})}}
	if len(hits)>0{same:=CloneState(state);return same,TransitionEvidence{Step:stepIndex,ContextID:context.ID,ContextHash:ContextHash(context),StateBeforeHash:StateHash(state),StateAfterHash:StateHash(same),Contradictions:hits},nil}
	next:=CloneState(state);keys:=make([]string,0,len(byKey));for key:=range byKey{keys=append(keys,key)};sort.Strings(keys);resolutions:=make([]Resolution,0,len(keys));for _,key:=range keys{value,resolution:=resolveEffects(key,byKey[key]);next.Values[key]=value;resolutions=append(resolutions,resolution)}
	return next,TransitionEvidence{Step:stepIndex,ContextID:context.ID,ContextHash:ContextHash(context),StateBeforeHash:StateHash(state),StateAfterHash:StateHash(next),FiredRules:fires,Resolutions:resolutions},nil
}

func Execute(initial State,machine Machine,contexts []Context)(Trajectory,error){
	if machine.Schema==""{machine.Schema=SchemaR1+".machine"};if err:=ValidateMachine(machine);err!=nil{return Trajectory{},err};if err:=ValidateState(initial);err!=nil{return Trajectory{},err};trajectory:=Trajectory{Schema:SchemaR1+".trajectory",Initial:CloneState(initial),States:[]State{CloneState(initial)}};current:=CloneState(initial)
	if len(contexts)>0{limit:=len(contexts);if limit>machine.MaxSteps{limit=machine.MaxSteps};for i:=0;i<limit;i++{next,ev,err:=Step(current,CloneContext(contexts[i]),machine,i+1);if err!=nil{return Trajectory{},err};trajectory.States=append(trajectory.States,CloneState(next));trajectory.Evidence=append(trajectory.Evidence,ev);if len(ev.Contradictions)>0{trajectory.Terminated="CONTRADICTION";trajectory.TraceHash=trajectoryHash(trajectory);return trajectory,nil};current=next};if len(contexts)>machine.MaxSteps{trajectory.Terminated="BUDGET_EXHAUSTED"}else{trajectory.Terminated="CONTEXTS_EXHAUSTED"};trajectory.TraceHash=trajectoryHash(trajectory);return trajectory,nil}
	empty:=Context{ID:"default",Values:map[string]Value{}};seen:=map[string]struct{}{StateHash(current):{}};for i:=0;i<machine.MaxSteps;i++{next,ev,err:=Step(current,empty,machine,i+1);if err!=nil{return Trajectory{},err};trajectory.States=append(trajectory.States,CloneState(next));trajectory.Evidence=append(trajectory.Evidence,ev);if len(ev.Contradictions)>0{trajectory.Terminated="CONTRADICTION";trajectory.TraceHash=trajectoryHash(trajectory);return trajectory,nil};if StateHash(next)==StateHash(current){trajectory.Terminated="FIXED_POINT";trajectory.TraceHash=trajectoryHash(trajectory);return trajectory,nil};hash:=StateHash(next);if _,ok:=seen[hash];ok{trajectory.Terminated="CYCLE";trajectory.TraceHash=trajectoryHash(trajectory);return trajectory,nil};seen[hash]=struct{}{};current=next};trajectory.Terminated="BUDGET_EXHAUSTED";trajectory.TraceHash=trajectoryHash(trajectory);return trajectory,nil
}
func validateContext(context Context)error{for key,value:=range context.Values{if strings.TrimSpace(key)==""{return fmt.Errorf("context key cannot be empty")};if !ValidateStatus(value.Status){return fmt.Errorf("context %q has invalid status %q",key,value.Status)}};return nil}
func matches(predicates []Predicate,state State,context Context)bool{for _,p:=range predicates{var value Value;var ok bool;if p.Scope=="context"{value,ok=context.Values[p.Key]}else{value,ok=state.Values[p.Key]};if !ok{value=Value{Status:StatusUnknown}};switch p.Op{case "data_eq":if value.Data!=p.Data{return false};case "data_ne":if value.Data==p.Data{return false};case "status_eq":if value.Status!=p.Status{return false};case "present":if value.Status!=StatusPresent{return false};case "not_present":if value.Status==StatusPresent{return false};default:return false}};return true}
func predicateParticipants(predicates []Predicate)[]string{seen:=map[string]struct{}{};for _,p:=range predicates{seen[p.Scope+":"+p.Key]=struct{}{}};out:=make([]string,0,len(seen));for value:=range seen{out=append(out,value)};sort.Strings(out);return out}
func effectKey(effect Effect)string{return fmt.Sprintf("%s|%s|%s|%s|%d",effect.Key,effect.Mode,effect.Status,effect.Data,effect.Delta)}
func resolveEffects(key string,effects []appliedEffect)(Value,Resolution){sort.Slice(effects,func(i,j int)bool{if effects[i].RuleID==effects[j].RuleID{return effectKey(effects[i].Effect)<effectKey(effects[j].Effect)};return effects[i].RuleID<effects[j].RuleID});ruleIDs:=[]string{};seen:=map[string]struct{}{};for _,item:=range effects{if _,ok:=seen[item.RuleID];!ok{seen[item.RuleID]=struct{}{};ruleIDs=append(ruleIDs,item.RuleID)}};for _,item:=range effects{if item.Effect.Mode=="inhibit"{value:=Value{Status:StatusInhibited,Data:item.Effect.Data};return value,Resolution{Key:key,Kind:"inhibition",RuleIDs:ruleIDs,Result:value}}};sets:=[]Value{};contrib:=[]int{};data:="";mixed:=false;for _,item:=range effects{switch item.Effect.Mode{case "set":sets=append(sets,Value{Status:item.Effect.Status,Data:item.Effect.Data});case "contribute":contrib=append(contrib,item.Effect.Delta);if data==""{data=item.Effect.Data}else if data!=item.Effect.Data{mixed=true}}};if len(sets)>0&&len(contrib)>0{v:=Value{Status:StatusUnknown};return v,Resolution{Key:key,Kind:"conflict",RuleIDs:ruleIDs,Contributions:contrib,Result:v}};if len(sets)>0{first:=sets[0];for _,candidate:=range sets[1:]{if candidate!=first{v:=Value{Status:StatusUnknown};return v,Resolution{Key:key,Kind:"conflict",RuleIDs:ruleIDs,Result:v}}};return first,Resolution{Key:key,Kind:"set",RuleIDs:ruleIDs,Result:first}};if len(contrib)>0{if mixed{v:=Value{Status:StatusUnknown};return v,Resolution{Key:key,Kind:"conflict",RuleIDs:ruleIDs,Contributions:contrib,Result:v}};total:=0;for _,delta:=range contrib{total+=delta};v:=Value{};kind:="contribution";if total==0{v=Value{Status:StatusCancelled,Data:data};kind="cancellation"}else if total>0{v=Value{Status:StatusPresent,Data:data}}else{v=Value{Status:StatusAbsent,Data:data}};return v,Resolution{Key:key,Kind:kind,RuleIDs:ruleIDs,Contributions:contrib,Result:v}};v:=Value{Status:StatusUnknown};return v,Resolution{Key:key,Kind:"conflict",RuleIDs:ruleIDs,Result:v}}
func trajectoryHash(trajectory Trajectory)string{clone:=trajectory;clone.TraceHash="";return hashJSON(clone)}
